# **What is NumPy?**
NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

We will only learn the basics of NumPy, to get started we need to install it!

# **Installation Instructions**
Install NumPy and Pandas in Jupyter notebook using Python package installer, *pip*.

**`$ python -m pip install <packages>`**

Eg: **`$ python -m pip install numpy`** , **`$ python -m pip install pandas`**

**pip** installs python packages in **any environment**.


# **Using NumPy**
Once you've installed NumPy you can import it as a library:

`import numpy as np`

Numpy has many built-in functions and capabilities like:
* Mathematical and logical operations on arrays can be performed.
* Fourier transforms and routines for shape manipulation.
* Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# **Numpy Arrays**

NumPy arrays are the main way we will use Numpy throughout the course.

The array object in NumPy is called *ndarray*. 

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## **Creating NumPy Arrays**
From a Python List
We can create an array by directly converting a list or list of lists:

In [ ]:
import numpy as np
my_list=np.array((1,2,3,4))             #1-Dimension
my_list
#print(my_list)

array([1, 2, 3, 4])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]          
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)                       #2-Dimension

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **dtype**
Each element in ndarray is an object of data-type object called dtype

You can also grab the data type of the object in the array:

In [ ]:
arr=np.array([1, 2, 3], dtype = complex) 

## **Built-in Methods**
There are lots of built-in ways to generate Arrays

### **Arange**

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,3)    #0=start, 11=End and 3=difference of this no. till the end

array([0, 3, 6, 9])

### **Zeros and ones**

Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### **Linspace**

Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,5)          #0=start , 10=end and 5=divides from total no. so as to make it in parts required 
#np.linspace(0,10,50)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### **Eye**

Creates an identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## **Random**
Random means something that can not be predicted logically.
Numpy also has lots of ways to create random number arrays:

### **rand**

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].

In [ ]:
np.random.rand(2)

array([0.91518215, 0.71311521])

In [ ]:
np.random.rand(5,5)

array([[0.89671316, 0.57271017, 0.87701553, 0.46672946, 0.90115116],
       [0.57577068, 0.49057729, 0.52163018, 0.38635841, 0.08472522],
       [0.28412048, 0.99656283, 0.6555327 , 0.00142091, 0.34017368],
       [0.30183253, 0.83144791, 0.20924504, 0.16461077, 0.85625596],
       [0.00640866, 0.06050975, 0.53580853, 0.92393551, 0.59554884]])

### **randn**

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

array([1.14880673, 0.14706695])

In [ ]:
np.random.randn(5,5)

array([[ 0.77166017, -0.41274959,  1.76729884, -1.3126536 ,  0.33204947],
       [ 1.11826642,  0.79064058, -0.0594278 , -0.68274008,  1.49487101],
       [-0.77602477, -1.63351779,  0.30164962, -0.41102622, -0.63675768],
       [ 0.45097378,  0.88248987,  0.17885212, -0.3869994 , -0.38556903],
       [ 0.21413599, -1.04288646, -0.80697649, -0.21236597, -0.91441518]])

### **randint**

Return random integers from low (inclusive) to high (exclusive).

In [ ]:
np.random.randint(1,100)

92

In [ ]:
np.random.randint(1,100,10)

array([35, 16,  1, 48, 22, 66, 28, 69, 90, 99])

### **choice**
Generates a random value based on an array of values given.

The choice() method takes an array as a parameter and randomly returns one of the values from choice given.

In [ ]:
np.random.choice([3, 5, 7, 9])

5

Add a size parameter to specify the shape of the array or creating n dimensions of array.

In [ ]:
np.random.choice([3, 5, 7, 9], size=(3, 5))

array([[9, 5, 3, 5, 7],
       [5, 3, 7, 3, 5],
       [9, 9, 5, 5, 5]])

Example:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([33, 27, 12, 23, 34, 34, 49, 23,  2, 48])

**max,min,argmax,argmin**

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([33, 27, 12, 23, 34, 34, 49, 23,  2, 48])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax()

6

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

8

### **Reshape**
Reshaping means changing the shape of an array.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### **Shape**
The shape of an array is the number of elements in each dimension.

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
#arr.reshape(25,1)
#arr.reshape(25,1).shape

# **NumPy Indexing and Selection**
In this, we will discuss how to select elements or groups of elements from an array.

In [ ]:
import numpy as np

In [ ]:
#Creating sample array
arr = np.arange(0,11)

In [ ]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### **Bracket Indexing and Selection**
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[9]

9

In [ ]:
#Get values in a range
arr[1:5]
#arr[:5]
#arr[1:]


array([1, 2, 3, 4])

### **Broadcasting**
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### **Indexing a 2D array (matrices)**
The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### **Fancy Indexing**
Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))

In [ ]:
#Length of array
arr_length = arr2d.shape[1]

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### **More Indexing Help**
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images.

### **Selection**
Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# **NumPy Operations**

## **Arithmetic**
You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
import numpy as np
arr = np.arange(0,10)

In [ ]:
arr + arr
#arr - arr
#arr * arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## **Universal Array Functions**
Numpy comes with many [universal array functions](https://numpy.org/doc/stable/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
np.sqrt(arr)                        #Taking Square Roots
#np.exp(arr)                        #Calcualting exponential (e^)
#np.log(arr)
#np.max(arr)                         #same as arr.max()
#np.sin(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])